ImpErpApi-All/ImpErpMvc/Models/ErrorViewModel.cs
using System;

namespace ImpErpMvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ImpErpApi-All/ImpErpMvc/Models/ProjectViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ImpErpCommonModel.Models;

namespace ImpErpMvc.Models
{
    public class ProjectViewModel
    {
        public string ProjectName { get; set; }
        public string Key { get; set; }
        public long Id { get; set; }
    }
}

ImpErpApi-All/ImpErpMvc/Models/ResultModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ImpErpMvc.Models
{
    public class ResultModel
    {
        public bool IsSuccess { get; set; }

        public dynamic Data { get; set; }

        public int Identity { get; set; }

        public string Message { get; set; }

        public string StatusCode { get; set; }
    }
}

ImpErpApi-All/ImpErpMvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ImpErpMvc.Models;

namespace ImpErpMvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ImpErpApi-All/ImpErpMvc/Controllers/JiraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ImpErpMvc.Models;
using Newtonsoft.Json;
using ImpErpMvc.Service;
using ImpErpCommon.Models;

namespace ImpErpMvc.Controllers
{
    public class JiraController : Controller
    {
        private ResultModel result;
        private ApiClient _apiClient;

        public JiraController()
        {
            _apiClient = new ApiClient();
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult GetAllProjects()
        {
            return View("GetAllProjects");
        }
        public JsonResult GetProjects()
        {
            var response = _apiClient.GetAllProject();
           
            var jsonList = JsonConvert.DeserializeObject<List<ProjectModel>>(response);

            var jsonResp = JsonConvert.SerializeObject(jsonList);

            return Json(jsonResp);            
            
        }
    }
}

ImpErpApi-All/ImpErpMvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <button id="btnTest" onclick="jiraInvoke()">ApiInvoke </button>
</div>

<script>


    function jiraInvoke() {
        alert("tet ss");

        var token = "mVGSX4DOlcT9A9VMHjT9DK86x1UNmV";
        var url = "https://api.tempo.io:443/core/3/worklogs?from=2019-11-10&to=2019-11-19";

        $.ajax({
            url: url,
            beforeSend: function (xhr) {
                //alert('before send');
                xhr.setRequestHeader("Authorization", "Bearer " + token)
            },

        })
            .done(function (data) {
                alert("done");
                //$.each(data, function (key, value) {
                //    // Do Something
                //})
            })
            .fail(function (jqXHR, textStatus) {
                alert("Error: " + textStatus);
            });
    }

</script>

ImpErpApi-All/ImpErpMvc/Views/Jira/GetAllProjects.cshtml
@{

    Layout = null;

    ViewData["Title"] = "GetAllProjects";
}
<head>
    <link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid.min.css" />
    <link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid-theme.min.css" />
    <script src="https://code.jquery.com/jquery-1.10.1.min.js"
            integrity="sha256-SDf34fFWX/ZnUozXXEH0AeB+Ip3hvRsjLwp6QNTEb3k="
            crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid.min.js"></script>

</head>
<h1>GetAllProjects</h1>

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <div id="jsGrid"></div>

</div>


<script>
    $(document).ready(function () {

        $("#jsGrid").jsGrid({
        width: "100%",
        height: "400px",

        autoload: true,
        inserting: true,
        editing: true,
        sorting: true,
        paging: true,

        controller: {
            loadData: function () {
                var d = $.Deferred();
                $.ajax({
                    type: "GET",
                    url: '@Url.Action("GetProjects", "Jira")',
                    //contentType: "application/json; charset=utf-8",
                    dataType: "json"
                }).done(function (response) {
                    d.resolve(JSON.parse(response));
                  //  alert(response);
                });
                return d.promise();
            }
        },
        fields: [
            { name: "ProjectName", type: "text", width: 150 },
            { name: "Key", type: "text", width: 100 },
            { name: "Id", type: "number", width: 50 }
        ]
    });

    });


</script>

ImpErpApi-All/ImpErpMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ImpErpMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ImpErpMvc</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - ImpErpMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>